Repository prgrms-web-devcourse-final-project/WEB2_3_ERoom_FE, pull requests merged in 2025-02, with the labels that each got.

#2 fix: pr템플릿 수정 #1
  .github/PULL_REQUEST_TEMPLATE.md
Labels: 🔨 Fix

#4 fix: 커밋 workflow 수정 #3
  .github/workflows/pr-commit-check.yml
Labels: 🔨 Fix

#9 design: 메인페이지 로그인상태, 레이아웃 디자인 #5
  package.json
  src/App.tsx
  src/components/MainPage/ScheduleBox.tsx
  src/components/MainPage/TodaySchedule.tsx
  src/components/layout/Header.tsx
  src/components/layout/Layout.tsx
  src/components/layout/Sidebar.tsx
  src/pages/MainPage.tsx
Labels: 🎨 Design

#11 [merge/ design_회원가입레이아웃_#8] fix: AuthLayout헤더추가 #8
  src/App.tsx
  src/components/common/Button.tsx
  src/components/layout/AuthLayout.tsx
  src/components/layout/Header.tsx
  src/pages/Main.tsx
  src/pages/SignIn.tsx
  src/pages/SignUp.tsx
  src/pages/SignUpCompanyInfo.tsx
Labels: 🎨 Design

#13 Design 프로젝트룸 레이아웃 #10
  src/App.tsx
  src/assets/icons/alarm.svg
  src/components/ProjectRoom/ProjectListBox.tsx
  src/components/ProjectRoom/ProjectProgressBar.tsx
  src/components/common/ParticipantIcon.tsx
  src/components/layout/Header.tsx
  src/components/layout/HeaderLayout.tsx
  src/pages/ProjectRoom.tsx
Labels: 🎨 Design

#15 [merge/ design_로그인회원가입-퍼블리싱_#12] Design 로그인회원가입 퍼블리싱 #12
  src/assets/auth_background.svg
  src/assets/google_logo.svg
  src/assets/kakao_logo.svg
  src/assets/mypage_background.svg
  src/components/common/Button.tsx
  src/components/layout/AuthLayout.tsx
  src/index.css
  src/pages/SignIn.tsx
  src/pages/SignUp.tsx
  src/pages/SignUpCompanyInfo.tsx
  src/styles/AuthLayout.css
Labels: 🎨 Design

#20 Desig 프로젝트 상세페이지 퍼블리싱 #14
  src/App.tsx
  src/assets/icons/newTaskIcon.svg
  src/assets/icons/outProjectDetail.svg
  src/assets/icons/sidebarAllicon.svg
  src/assets/icons/sidebarManagerIcon.svg
  src/assets/icons/sidebarMeetIcon.svg
  src/components/ProjectRoom/ProjectListBox.tsx
  src/components/Task/TaskBox.tsx
  src/components/Task/TaskList.tsx
  src/components/layout/Sidebar.tsx
  src/index.css
  src/pages/ProjectRoom/ProjectRoom.tsx
  src/pages/ProjectRoom/ProjectRoomDetail.tsx
Labels: 🎨 Design

#22 [merge/ design_알람-모달_#19] design: 알람닫기버튼추가 #19
  src/App.tsx
  src/components/AlamModal/AlarmBox.tsx
  src/components/common/Button.tsx
  src/components/layout/Header.tsx
  src/components/modals/AlarmModal.tsx
  src/index.css
  src/pages/SignUpCompanyInfo.tsx
Labels: 🎨 Design

#24 Design 프로젝트페이지/사이드바 수정 #21
  package.json
  src/assets/icons/sideLeftArrow.svg
  src/assets/icons/sideRightArrow.svg
  src/components/ProjectRoom/ProjectListBox.tsx
  src/components/layout/Layout.tsx
  src/components/layout/Sidebar.tsx
  src/components/modals/AllProjectOutModal.tsx
  src/index.css
  src/pages/MainPage.tsx
  src/pages/ProjectRoom/ProjectRoom.tsx
Labels: 🎨 Design

#27 [merge/design_알람모달-수정_#26] design: 알람모달문구수정 #26
  src/components/AlamModal/AlarmBox.tsx
  src/components/modals/AlarmModal.tsx
  src/index.css
Labels: 🎨 Design

#28 Feat: 캘린더 임시데이터 삽입, 드래그 기능, 커스텀/ 메인페이지 디자인 수정 #25
  package.json
  src/components/MainPage/Calendar.tsx
  src/components/MainPage/ScheduleBox.tsx
  src/components/MainPage/TodaySchedule.tsx
  src/pages/MainPage.tsx
  src/styles/Calandar.css
Labels: 🎨 Design, 🌟 Feat

#30 Design: 관리자 대시보드 퍼블리싱 #29
  package.json
  src/App.tsx
  src/assets/icons/dashboard/accountIcon.svg
  src/assets/icons/dashboard/dashboardIcon.svg
  src/assets/icons/dashboard/payIcon.svg
  src/assets/icons/dashboard/projectIcon.svg
  src/assets/icons/dashboard/tagIcon.svg
  src/assets/icons/dashboard/taskIcon.svg
  src/components/Admin/Chart.tsx
  src/components/Admin/DashBoard.tsx
  src/components/layout/Layout.tsx
  src/components/layout/Sidebar.tsx
  src/pages/Admin.tsx
Labels: 🎨 Design

#34 <merge/design_프로젝트상세-미팅룸_#33> design: 프로젝트상세-미팅룸 #33
  src/App.tsx
  src/components/MeetingRoom/MeetingRoomChatBox.tsx
  src/pages/ProjectRoom/ProjectRoomDetail.tsx
Labels: 🎨 Design

#36 <merge/refactor_채팅창-컴포넌트-분리_#35>refactor: 채팅창컴포넌트분리 #35
  src/components/MeetingRoom/MeetingRoomChatBox.tsx
  src/components/MeetingRoom/MeetingRoomMessage.tsx
Labels: 🛠️ Refactor

#38 Desgin: 사이드바/헤더 레이아웃 수정 #31
  src/assets/icons/headerLogo.svg
  src/components/Admin/Chart.tsx
  src/components/Admin/DashBoard.tsx
  src/components/layout/Header.tsx
  src/components/layout/Layout.tsx
  src/components/layout/Sidebar.tsx
  src/pages/MainPage.tsx
  src/pages/ProjectRoom/ProjectRoomDetail.tsx
Labels: 🎨 Design

#40 design: 프로젝트 태그 디자인/관리자 페이지 배경 수정 #39
  src/components/Admin/DashBoard.tsx
  src/components/ProjectRoom/ProjectListBox.tsx
Labels: 🎨 Design

#43 Feat: 캘린더 mock데이터 설정, url수정 #42
  .gitignore
  package.json
  src/App.tsx
  src/api/api.ts
  src/components/AlamModal/AlarmBox.tsx
  src/components/MainPage/Calendar.tsx
  src/components/MeetingRoom/MeetingRoomChatBox.tsx
  src/components/ProjectRoom/ProjectListBox.tsx
  src/components/layout/Header.tsx
  src/components/layout/Sidebar.tsx
  src/main.tsx
  src/pages/SignIn.tsx
  src/types/projectList.d.ts
  src/utils/api/getProjectList.ts
  src/utils/calendar/dragChange.ts
Labels: 🌟 Feat

#45 <Merge/design_관리자-계정관리페이지_#37>Design 관리자 계정관리페이지 #37
  src/assets/icons/checked_box.svg
  src/assets/icons/delete.svg
  src/assets/icons/edit.svg
  src/assets/icons/end_page_off.svg
  src/assets/icons/end_page_on.svg
  src/assets/icons/next_page_off.svg
  src/assets/icons/next_page_on.svg
  src/assets/icons/pre_page_off.svg
  src/assets/icons/pre_page_on.svg
  src/assets/icons/save.svg
  src/assets/icons/search.svg
  src/assets/icons/start_page_off.svg
  src/assets/icons/start_page_on.svg
  src/assets/icons/unchecked_box.svg
  src/components/Admin/Account.tsx
  src/components/Admin/AccountList.tsx
  src/components/Admin/Pagination.tsx
  src/components/common/AdminButton.tsx
  src/index.css
  src/pages/Admin.tsx
Labels: 🎨 Design

#49 <Merge/design_마이페이지및알람모달-수정_#46> design: 마이페이지알람모달수정 #46
  src/assets/mypage_background.svg
  src/components/layout/Header.tsx
  src/pages/MyPage.tsx
Labels: 🎨 Design

#52 Design: 프로젝트 상세페이지 디자인 수정 #44
  src/assets/icons/sideCheckIcon.svg
  src/components/ProjectRoom/ProjectListBox.tsx
  src/components/Task/TaskBox.tsx
  src/components/Task/TaskList.tsx
  src/components/layout/Layout.tsx
  src/components/layout/ManagerCheckBox.tsx
  src/components/layout/Sidebar.tsx
  src/index.css
  src/pages/ProjectRoom/ProjectRoom.tsx
  src/pages/ProjectRoom/ProjectRoomDetail.tsx
Labels: 🎨 Design

#51 <Merge/design_계정관리페이지-세부수정_#50>design: 계정관리페이지수정 #50
  src/assets/icons/restore_account.svg
  src/components/Admin/Account.tsx
  src/components/Admin/AccountList.tsx
  src/pages/Admin.tsx
Labels: 🎨 Design

#57 Design 관리자 프로젝트관리 퍼블리싱 #54
  src/components/Admin/Account/Account.tsx
  src/components/Admin/Account/AccountList.tsx
  src/components/Admin/Pagination.tsx
  src/components/Admin/Project/Project.tsx
  src/components/Admin/Project/ProjectList.tsx
  src/components/Admin/Project/ProjectStatusBox.tsx
  src/pages/Admin.tsx
Labels: 🎨 Design

#62 <merge/design_업무생성편집-모달_#61>design: 업무생성편집-모달_#61
  src/components/Task/TaskBox.tsx
  src/components/Task/TaskList.tsx
  src/components/modals/CreateProjectModal.tsx
  src/components/modals/CreateTaskModal.tsx
  src/components/modals/UpdateTaskModal.tsx
Labels: 🎨 Design

#64 Design 관리자페이지 업무관리 퍼블리싱 #59
  src/components/Admin/Account/AdminAccount.tsx
  src/components/Admin/Account/AdminAccountList.tsx
  src/components/Admin/ProgressStatusBox.tsx
  src/components/Admin/Project/AdminProject.tsx
  src/components/Admin/Project/AdminProjectList.tsx
  src/components/Admin/Project/ProjectStatusBox.tsx
  src/components/Admin/Task/AdminTask.tsx
  src/components/Admin/Task/AdminTaskList.tsx
  src/constants/status.ts
  src/pages/Admin.tsx
  src/utils/progressType.ts
Labels: 🎨 Design, 🔨 Fix

#66 FEAT. 프로젝트 편집모달_#55
  src/components/EditProjectModal/SelectCategory.tsx
  src/components/EditProjectModal/SelectMember.tsx
  src/components/EditProjectModal/SelectProject.tsx
  src/components/EditProjectModal/WordCloud.tsx
  src/components/EditProjectModal/WriteProjectName.tsx
  src/components/ProjectRoom/ProjectListBox.tsx
  src/components/modals/ChangeProjectModal.tsx
  src/components/modals/EditProjectModal.tsx
  src/pages/ProjectRoom/ProjectRoom.tsx
Labels: 🔥 Bug, 🌟 Feat, 🔨 Fix

#68 <Merge/design_회의록-모달_#63>design: 회의록모달 #63
  package.json
  src/assets/animations/loading_note.json
  src/components/MeetingRoom/MeetingRoomChatBox.tsx
  src/components/NoteList/DayNoteList.tsx
  src/components/NoteList/NoteListBox.tsx
  src/components/modals/CreateAINoteModal.tsx
  src/components/modals/CreateNotePeriodModal.tsx
  src/components/modals/NoteDetailModal.tsx
  src/components/modals/NoteListModal.tsx
Labels: 🎨 Design

#70 feat: 프로젝트 리스트 데이터 적용 #65
  package.json
  src/components/MainPage/Calendar.tsx
  src/components/ProjectRoom/ProjectListBox.tsx
  src/components/layout/Sidebar.tsx
  src/components/modals/CreateTaskModal.tsx
  src/components/modals/UpdateTaskModal.tsx
  src/index.css
  src/main.tsx
  src/pages/ProjectRoom/ProjectRoom.tsx
  src/pages/ProjectRoom/ProjectRoomDetail.tsx
  src/types/projectList.d.ts
  src/utils/api/getProjectDetail.ts
Labels: 🌟 Feat

#72 FEAT/FIX: 프로젝트생성편집모달에 기간설정 추가
  src/components/EditProjectModal/DateTimeSelect.tsx
  src/components/EditProjectModal/SelectCategory.tsx
  src/components/EditProjectModal/SelectMember.tsx
  src/components/ProjectRoom/ProjectListBox.tsx
  src/components/modals/ChangeProjectModal.tsx
  src/components/modals/CreateNotePeriodModal.tsx
  src/components/modals/CreateTaskModal.tsx
  src/components/modals/EditProjectModal.tsx
  src/components/modals/UpdateTaskModal.tsx
  src/pages/ProjectRoom/ProjectRoom.tsx
Labels: 🌟 Feat, 🔨 Fix

#74 Fixfeat 각 페이지별 세부조정 및 추가 #73
  src/components/ProjectRoom/ProjectListBox.tsx
  src/components/ProjectRoom/ProjectProgressBar.tsx
  src/components/Task/TaskBox.tsx
  src/components/Task/TaskList.tsx
  src/components/modals/CreateTaskModal.tsx
  src/components/modals/EditProjectModal.tsx
  src/components/modals/UpdateTaskModal.tsx
  src/index.css
  src/pages/ProjectRoom/ProjectRoom.tsx
  src/pages/ProjectRoom/ProjectRoomDetail.tsx
Labels: 🔥 Bug, 🌟 Feat, 🔨 Fix

#75 Feat: 프로젝트 상세 데이터 적용 #71
  src/components/MainPage/Calendar.tsx
  src/components/Task/TaskBox.tsx
  src/components/Task/TaskList.tsx
  src/components/layout/Sidebar.tsx
  src/constants/status.ts
  src/pages/ProjectRoom/ProjectRoomDetail.tsx
  src/types/projectDetailList.d.ts
  src/utils/api/getProjectDetail.ts
Labels: 🌟 Feat

#77 Fixfeat 각 페이지별 세부수정사항변경 #76
  src/components/Admin/Account/AdminAccount.tsx
  src/components/Admin/Account/AdminAccountList.tsx
  src/components/Admin/Chart.tsx
  src/components/Admin/Pagination.tsx
  src/components/Admin/ProgressStatusBox.tsx
  src/components/Admin/Project/AdminProject.tsx
  src/components/Admin/Project/AdminProjectList.tsx
  src/components/AlamModal/AlarmBox.tsx
  src/components/EditProjectModal/DateTimeSelect.tsx
  src/components/EditProjectModal/SelectCategory.tsx
  src/components/EditProjectModal/SelectMember.tsx
  src/components/EditProjectModal/SelectProject.tsx
  src/components/EditProjectModal/WordCloud.tsx
  src/components/EditProjectModal/WriteProjectName.tsx
  src/components/MeetingRoom/MeetingRoomChatBox.tsx
  src/components/MeetingRoom/MeetingRoomMessage.tsx
  src/components/ProjectRoom/ProjectListBox.tsx
  src/components/Task/TaskBox.tsx
  src/components/Task/TaskList.tsx
  src/components/common/AdminButton.tsx
  src/components/common/Button.tsx
  src/components/common/ParticipantIcon.tsx
  src/components/modals/AlarmModal.tsx
  src/components/modals/AllProjectOutModal.tsx
  src/components/modals/CreateNotePeriodModal.tsx
  src/components/modals/CreateTaskModal.tsx
  src/components/modals/EditProjectModal.tsx
  src/components/modals/UpdateTaskModal.tsx
  src/dummyData/dummy.ts
  src/pages/MyPage.tsx
  src/pages/ProjectRoom/ProjectRoomDetail.tsx
  src/types/admin.d.ts
  src/types/alarm.d.ts
  src/types/button.d.ts
  src/types/category.d.ts
  src/types/date.d.ts
  src/types/member.d.ts
  src/types/messages.d.ts
  src/types/project.d.ts
  src/types/task.d.ts
  src/types/wordCloud.d.ts
Labels: 🌟 Feat, 🔨 Fix

#80 Featfix 미완성퍼블리싱작업 #78
  src/App.tsx
  src/components/ProjectRoom/ProjectListBox.tsx
  src/components/layout/AuthLayout.tsx
  src/components/layout/Header.tsx
  src/components/layout/Sidebar.tsx
  src/components/modals/ConfirmModal.tsx
  src/context/AuthContext.tsx
  src/pages/MainPage.tsx
  src/pages/MyPage.tsx
  src/pages/SignIn.tsx
  src/pages/SignUp.tsx
  src/pages/SignUpCompanyInfo.tsx
  src/types/loggedIn.d.ts
Labels: 🌟 Feat, 🔨 Fix

#82 <Merge/design_관리자-태그관리페이지_#69>Design 관리자 태그관리페이지 #69
  src/assets/button/add_tag.svg
  src/components/Admin/Tag/AdminTag.tsx
  src/components/Admin/Tag/AdminTagAdd.tsx
  src/components/Admin/Tag/AdminTagList.tsx
  src/pages/Admin.tsx
Labels: 🎨 Design

#84 feat: 프로젝트 생성 기능구현 #79
  src/components/EditProjectModal/DateTimeSelect.tsx
  src/components/EditProjectModal/SelectMember.tsx
  src/components/EditProjectModal/WriteProjectName.tsx
  src/components/MainPage/TodaySchedule.tsx
  src/components/modals/EditProjectModal.tsx
  src/types/date.d.ts
  src/types/member.d.ts
  src/types/project.d.ts
  src/utils/api/createProject.ts
Labels: 🌟 Feat

#86 Fixfeat 1차 qa 확인모달적용 및 스크롤바스타일수정 #81
  package.json
  src/App.tsx
  src/assets/defaultImg.svg
  src/assets/icons/exitMeetingRoom.svg
  src/components/Task/TaskBox.tsx
  src/components/layout/Header.tsx
  src/components/modals/ConfirmModal.tsx
  src/context/AuthContext.tsx
  src/index.css
  src/pages/MainPage.tsx
  src/pages/MeetingRoom/MeetingRoom.tsx
  src/pages/MyPage.tsx
  src/pages/SignIn.tsx
  src/pages/SignUpCompanyInfo.tsx
  src/store/authStore.ts
Labels: 🌟 Feat, 🔨 Fix

#87 <merge/fixfeat_1차qa_채팅창및회의록-수정_#83>fix:1차qa채팅창및회의록수정 #83
  package.json
  src/components/MeetingRoom/MeetingRoomChatBox.tsx
  src/components/NoteList/DayNoteList.tsx
  src/components/NoteList/NoteListBox.tsx
  src/components/layout/Header.tsx
  src/components/modals/CreateNotePeriodModal.tsx
  src/components/modals/NoteDetailModal.tsx
Labels: 🔨 Fix

#88 feat: 로그인 기능 임시구현 #85
  src/App.tsx
  src/components/common/Button.tsx
  src/components/layout/Header.tsx
  src/pages/MainPage.tsx
  src/pages/ProtectedRoute.tsx
  src/pages/SignIn.tsx
  src/pages/SignUpCompanyInfo.tsx
  src/store/authStore.ts
Labels: 🌟 Feat

#90 fix: 프로젝트리스트 수정데이터 반영 #89
  src/components/MainPage/Calendar.tsx
  src/components/ProjectRoom/ProjectListBox.tsx
  src/components/ProjectRoom/ProjectProgressBar.tsx
  src/components/Task/TaskBox.tsx
  src/components/common/ParticipantIcon.tsx
  src/components/modals/EditProjectModal.tsx
  src/constants/calendarColors.ts
  src/types/button.d.ts
  src/types/projectList.d.ts
  src/utils/randomColor.ts
Labels: 🔨 Fix

#94 <merge/fix_1차-qa-미팅룸-및-관리자페이지_#92>fix: 1차qa 미팅룸및관리자페이지 #92
  .env
  src/components/Admin/Account/AdminAccount.tsx
  src/components/Admin/DashBoard.tsx
  src/components/Admin/ProgressStatusBox.tsx
  src/components/Admin/Project/AdminProject.tsx
  src/components/Admin/Task/AdminTask.tsx
  src/components/MeetingRoom/MeetingRoomChatBox.tsx
  src/components/layout/Sidebar.tsx
  src/pages/ProjectRoom/ProjectRoomDetail.tsx
Labels: 🔨 Fix

#96 fix: 1차 QA 캘린더 높이조절 #93
  .gitignore
  src/components/MainPage/Calendar.tsx
Labels: 🎨 Design, 🔨 Fix

#112 <Merge/feat_api-연동-테스트2_#110>feat: 임시로그인api #110
  package.json
  src/api/admin.ts
  src/api/api.ts
  src/api/auth.ts
  src/api/project.ts
  src/pages/MyPage.tsx
  src/pages/ProjectRoom/ProjectRoom.tsx
  src/pages/SignIn.tsx
  vite.config.ts
Labels: 🌟 Feat

#114 Feat 프로젝트 상세 구현 #111
  src/components/Task/TaskBox.tsx
  src/components/Task/TaskList.tsx
  src/components/layout/Layout.tsx
  src/components/layout/ManagerCheckBox.tsx
  src/components/layout/Sidebar.tsx
  src/pages/MainPage.tsx
  src/pages/ProjectRoom/ProjectRoomDetail.tsx
  src/store/sideMemberStore.ts
  src/types/projectDetailList.d.ts
  src/types/task.d.ts
  src/utils/api/getProjectDetail.ts
Labels: 🌟 Feat

#115 Fix 디바운스처리및업무생성편집모달데이터 #97
  package.json
  src/api/api.ts
  src/api/task.ts
  src/assets/icons/save2.svg
  src/assets/icons/search2.svg
  src/components/EditProjectModal/DateTimeSelect.tsx
  src/components/EditProjectModal/SelectCategory.tsx
  src/components/EditProjectModal/SelectMember.tsx
  src/components/EditProjectModal/WriteProjectName.tsx
  src/components/ProjectRoom/ProjectListBox.tsx
  src/components/Task/TaskList.tsx
  src/components/modals/CreateTaskModal.tsx
  src/components/modals/EditProjectModal.tsx
  src/components/modals/UpdateTaskModal.tsx
  src/dummyData/dummy.ts
  src/pages/ProjectRoom/ProjectRoom.tsx
  src/pages/ProjectRoom/ProjectRoomDetail.tsx
  src/pages/SignIn.tsx
  src/types/category.d.ts
  src/types/member.d.ts
  src/types/project.d.ts
  src/types/projectList.d.ts
  src/types/task.d.ts
  src/utils/debounce.ts
Labels: 🌟 Feat, 🔨 Fix

#118 FEAT: 프로젝트 API 생성
  src/api/project.ts
  src/api/task.ts
  src/components/ProjectRoom/ProjectListBox.tsx
  src/components/ProjectRoom/ProjectProgressBar.tsx
  src/components/layout/Layout.tsx
  src/components/layout/Sidebar.tsx
  src/pages/ProjectRoom/ProjectRoomDetail.tsx
  src/types/projectDetailList.d.ts
Labels: 🌟 Feat

#119 <Merge/feat_api-호출_#116>feat: API함수추가 #116
  src/api/admin.ts
  src/api/api.ts
  src/api/meetingroom.ts
  src/api/project.ts
  src/api/search.ts
  src/components/modals/EditProjectModal.tsx
  src/pages/ProjectRoom/ProjectRoom.tsx
  src/types/messages.d.ts
  src/types/project.d.ts
Labels: 🌟 Feat

#123 <Merge/feat_검색api함수-추가_#120>feat: 검색API함수 추가 #120
  src/api/project.ts
  src/api/search.ts
  src/components/modals/EditProjectModal.tsx
  src/pages/ProjectRoom/ProjectRoom.tsx
  src/types/project.d.ts
Labels: 🌟 Feat

#126 FIX: 프로젝트 편집 모달 데이터 연결 및 진행상태 추가
  src/api/project.ts
  src/components/EditProjectModal/SelectCategory.tsx
  src/components/ProjectRoom/ProjectListBox.tsx
  src/components/modals/ConfirmModal.tsx
  src/components/modals/EditProjectModal.tsx
  src/pages/ProjectRoom/ProjectRoom.tsx
  src/pages/ProjectRoom/ProjectRoomDetail.tsx
  src/types/category.d.ts
  src/types/member.d.ts
  src/types/project.d.ts
  src/types/projectList.d.ts
Labels: 🔨 Fix

#129 Feat 프로젝트 수정api연결 #125
  src/api/project.ts
  src/api/search.ts
  src/components/EditProjectModal/SelectCategory.tsx
  src/components/EditProjectModal/SelectMember.tsx
  src/components/EditProjectModal/WriteProjectName.tsx
  src/components/MainPage/Calendar.tsx
  src/components/ProjectRoom/ProjectListBox.tsx
  src/components/modals/EditProjectModal.tsx
  src/constants/calendarColors.ts
  src/types/project.d.ts
  src/utils/calendar/dragChange.ts
  src/utils/progressType.ts
Labels: 🌟 Feat

#133 <Merge/feat_채팅방-및-프로젝트멤버검색_#113>Feat 채팅방 및 프로젝트멤버검색 #113
  package.json
  src/App.tsx
  src/api/api.ts
  src/components/MeetingRoom/MeetingRoomChatBox.tsx
  src/components/MeetingRoom/MeetingRoomMessage.tsx
  src/components/MeetingRoom/MeetingRoomProjectBox.tsx
  src/components/common/Loading.tsx
  src/constants/socialLogin.ts
  src/hooks/useKakaoLogin.ts
  src/pages/KakaoRedirect.tsx
  src/pages/MeetingRoom/MeetingRoom.tsx
  src/pages/ProjectRoom/ProjectRoomDetail.tsx
  src/pages/SignIn.tsx
  src/store/authStore.ts
  src/types/member.d.ts
  src/types/messages.d.ts
  src/types/social.d.ts
  vite.config.ts
Labels: 🌟 Feat

#131 Fix 프로젝트 생성모달 제목/빈칸 #130
  src/api/api.ts
  src/components/EditProjectModal/WriteProjectName.tsx
  src/components/MainPage/Calendar.tsx
  src/components/modals/EditProjectModal.tsx
  src/types/project.d.ts
Labels: 🌟 Feat

#135 feat: admin페이지 대시보드 데이터 연결 #132
  src/api/admin.ts
  src/components/Admin/Chart.tsx
  src/components/Admin/DashBoard.tsx
  src/components/MeetingRoom/MeetingRoomChatBox.tsx
  src/components/MeetingRoom/MeetingRoomMessage.tsx
  src/types/admin.d.ts
Labels: 🌟 Feat

#138 Feat 관리자 계정관리 기능구현 #136
  src/api/admin.ts
  src/components/Admin/Account/AdminAccount.tsx
  src/components/Admin/Account/AdminAccountList.tsx
  src/types/admin.d.ts
Labels: 🌟 Feat

#142 <Merge/feat_회의록-생성_#137>feat: 회의록생성 #137
  src/api/meetingroom.ts
  src/components/MeetingRoom/MeetingRoomChatBox.tsx
  src/components/MeetingRoom/MeetingRoomMessage.tsx
  src/components/modals/CreateAINoteModal.tsx
  src/components/modals/CreateNotePeriodModal.tsx
  src/components/modals/NoteListModal.tsx
  src/pages/SignIn.tsx
  src/types/messages.d.ts
  src/types/projectDetailList.d.ts
Labels: 🌟 Feat

#141 Feat 구글 로그인 api 연동 및 업무생성수정삭제 #128
  src/api/task.ts
  src/components/EditProjectModal/SelectMember.tsx
  src/components/EditProjectModal/WriteProjectName.tsx
  src/components/ProjectRoom/ProjectListBox.tsx
  src/components/Task/TaskBox.tsx
  src/components/Task/TaskList.tsx
  src/components/layout/Sidebar.tsx
  src/components/modals/ConfirmModal.tsx
  src/components/modals/CreateTaskModal.tsx
  src/components/modals/UpdateTaskModal.tsx
  src/constants/calendarColors.ts
  src/pages/MainPage.tsx
  src/pages/ProjectRoom/ProjectRoomDetail.tsx
  src/pages/SignIn.tsx
  src/types/member.d.ts
  src/types/task.d.ts
  src/utils/signInGoogle/getAccessToken.ts
  src/utils/signInGoogle/getUserInfo.ts
Labels: 🌟 Feat, 🔨 Fix

#145 Fix 서버주소 수정 #139
  src/api/admin.ts
  src/api/api.ts
  src/components/EditProjectModal/SelectCategory.tsx
  src/components/MainPage/Calendar.tsx
  src/components/ProjectRoom/ProjectListBox.tsx
  src/components/modals/EditProjectModal.tsx
  src/types/category.d.ts
  src/types/project.d.ts
  src/types/projectList.d.ts
  src/utils/calendar/dragChange.ts
  vite.config.ts
Labels: 🔨 Fix

#147 fix: 사이드바 오류, 캘린더 드래그 함수 오류 수정 #146
  src/components/MainPage/Calendar.tsx
  src/components/layout/Sidebar.tsx
  src/utils/calendar/dragChange.ts
Labels: 🔨 Fix

#150 fix: 구글 로그인 구현(id/access 토큰)
  src/pages/MainPage.tsx
  src/pages/SignIn.tsx
  src/utils/signInGoogle/getAccessToken.ts
Labels: 🌟 Feat, 🔨 Fix

#152 <Merge/feat_회의록-생성-테스트_#149>Feat 회의록 생성 테스트 #149
  src/components/MeetingRoom/MeetingRoomChatBox.tsx
  src/components/MeetingRoom/MeetingRoomMessage.tsx
  src/components/modals/CreateAINoteModal.tsx
  src/pages/SignIn.tsx
Labels: 🌟 Feat
