Repository prgrms-web-devcourse-final-project/WEB2_3_ERoom_FE, pull requests merged in 2025-03, with the labels that each got.

#154 Feat 프로젝트 나가기/삭제 구현 #148
  src/api/project.ts
  src/api/search.ts
  src/components/EditProjectModal/SelectCategory.tsx
  src/components/EditProjectModal/SelectMember.tsx
  src/components/ProjectRoom/ProjectListBox.tsx
  src/components/modals/ConfirmModal.tsx
  src/components/modals/EditProjectModal.tsx
  src/pages/SignIn.tsx
  src/types/member.d.ts
  src/types/projectList.d.ts
Labels: 🌟 Feat

#157 design: 메인페이지 비로그인 디자인 #156
  src/assets/guestMainBg.svg
  src/components/MainPage/GuestMain.tsx
  src/index.css
  src/pages/MainPage.tsx
Labels: 🎨 Design

#158 Feat 관리자 프로젝트 관리 기능구현 #140
  src/api/admin.ts
  src/components/Admin/Account/AdminAccountList.tsx
  src/components/Admin/Button/AdminDeleteBtn.tsx
  src/components/Admin/Button/AdminEditCancelBtn.tsx
  src/components/Admin/DashBoard.tsx
  src/components/Admin/Project/AdminProject.tsx
  src/components/Admin/Project/AdminProjectList.tsx
  src/types/admin.d.ts
Labels: 🌟 Feat

#160 <Merge/feat_회의록-추가-기능-구현_#155>feat: 회의록 추가구현 #155
  src/api/meetingroom.ts
  src/components/MeetingRoom/MeetingRoomChatBox.tsx
  src/components/NoteList/DayNoteList.tsx
  src/components/NoteList/NoteListBox.tsx
  src/components/modals/CreateAINoteModal.tsx
  src/components/modals/CreateNotePeriodModal.tsx
  src/components/modals/NoteDetailModal.tsx
  src/components/modals/NoteListModal.tsx
  src/types/messages.d.ts
  src/utils/aiNote/dateUtils.ts
Labels: 🌟 Feat

#162 Feat 프로젝트 수정권한 처리 #159
  src/api/project.ts
  src/components/EditProjectModal/SelectCategory.tsx
  src/components/EditProjectModal/SelectMember.tsx
  src/components/MainPage/Calendar.tsx
  src/components/ProjectRoom/ProjectListBox.tsx
  src/components/modals/EditProjectModal.tsx
  src/types/member.d.ts
  src/utils/calendar/dragChange.ts
Labels: 🌟 Feat, 🔨 Fix

#168 Bug 업무담당자 미배정 오류 #165
  src/components/EditProjectModal/SelectMember.tsx
  src/components/modals/CreateTaskModal.tsx
  src/types/member.d.ts
  src/types/project.d.ts
Labels: 🔥 Bug

#171 Feat 구글 로그인 테스트 #170
  src/api/api.ts
  src/api/auth.ts
  src/components/layout/Header.tsx
  src/components/layout/Sidebar.tsx
  src/pages/SignIn.tsx
  src/pages/SignUpCompanyInfo.tsx
  src/store/authStore.ts
  src/types/social.d.ts
Labels: 🌟 Feat

#174 bug: 구글 로그인 버그 수정
  src/api/api.ts
  src/api/auth.ts
  src/components/ProjectRoom/ProjectListBox.tsx
  src/components/layout/Header.tsx
  src/components/layout/Layout.tsx
  src/pages/MainPage.tsx
  src/pages/ProjectRoom/ProjectRoomDetail.tsx
  src/pages/ProtectedRoute.tsx
  src/pages/SignIn.tsx
  src/pages/SignUpCompanyInfo.tsx
  src/store/authStore.ts
Labels: 🔥 Bug

#176 Feat 프로젝트 없음 디자인/관리자수정 #167
  src/App.tsx
  src/components/Admin/Project/AdminProject.tsx
  src/components/Admin/Project/AdminProjectList.tsx
  src/components/EditProjectModal/SelectMember.tsx
  src/components/MainPage/Calendar.tsx
  src/components/ProjectRoom/ProjectListBox.tsx
  src/pages/NotFound.tsx
  src/pages/ProjectRoom/ProjectRoom.tsx
  src/types/admin.d.ts
  src/utils/api/getProjectDetail.ts
Labels: 🌟 Feat, 🔨 Fix

#178 <Merge/feat_로그인후-api-테스트_#172> feat: 웹소켓토큰인증 #172
  src/App.tsx
  src/components/MeetingRoom/MeetingRoomChatBox.tsx
Labels: 🌟 Feat

#180 feat: 관리자 업무 데이터 연결 및 수정
  src/api/admin.ts
  src/components/Admin/Task/AdminTask.tsx
  src/components/Admin/Task/AdminTaskList.tsx
  src/components/Task/TaskList.tsx
  src/components/modals/UpdateTaskModal.tsx
  src/types/task.d.ts
Labels: 🌟 Feat

#182 Fix 구글 로그인 커스텀 훅 및 signin 컴포넌트 정리 #181
  src/hooks/useGoogleLogin.ts
  src/pages/SignIn.tsx
Labels: 🔨 Fix

#184 <Merge/feat_알람-기능-로그인제외_#166>Feat 알람 기능 로그인제외 #166
  src/App.tsx
  src/api/alarm.ts
  src/components/MeetingRoom/MeetingRoomChatBox.tsx
  src/components/MeetingRoom/MeetingRoomMessage.tsx
  src/components/modals/AlarmModal.tsx
  src/store/useWebSocketStore.ts
Labels: 🌟 Feat

#186 <Merge/fix_alert-모달로-변경_#185> fix: alert을 모달로 변경 #185
  src/components/Admin/Account/AdminAccount.tsx
  src/components/Admin/Project/AdminProject.tsx
  src/components/EditProjectModal/SelectMember.tsx
  src/components/MainPage/Calendar.tsx
  src/components/ProjectRoom/ProjectListBox.tsx
  src/components/common/AlertModal.tsx
  src/components/modals/ConfirmModal.tsx
  src/components/modals/CreateTaskModal.tsx
  src/pages/SignUpCompanyInfo.tsx
Labels: 🔨 Fix

#188 <Merge/design_alertmodal-버튼-생상-수정_#187>design: 알럿모달버튼색상수정 #187
  src/components/ProjectRoom/ProjectListBox.tsx
  src/components/common/AlertModal.tsx
Labels: 🎨 Design

#192 Feat 관리자페이지 업무 삭제 메인페이지 업무 기능 #183
  src/api/admin.ts
  src/components/Admin/Task/AdminTask.tsx
  src/components/Admin/Task/AdminTaskList.tsx
  src/components/EditProjectModal/SelectMember.tsx
  src/components/Task/TaskBox.tsx
  src/components/Task/TaskList.tsx
  src/components/layout/ManagerCheckBox.tsx
  src/components/layout/Sidebar.tsx
  src/components/modals/ConfirmModal.tsx
  src/components/modals/CreateTaskModal.tsx
  src/components/modals/SimpleAlertModal.tsx
  src/pages/ProjectRoom/ProjectRoomDetail.tsx
  src/types/projectDetailList.d.ts
  src/types/projectList.d.ts
  src/types/task.d.ts
Labels: 🌟 Feat, 🔨 Fix

#194 Feat 관리자페이지 태그부분 구현 #179
  src/api/admin.ts
  src/api/adminCategory.ts
  src/api/adminDetailTag.ts
  src/api/adminSubCategory.ts
  src/components/Admin/Button/AdminDeleteBtn.tsx
  src/components/Admin/Button/AdminEditCancelBtn.tsx
  src/components/Admin/Tag/AdminTag.tsx
  src/components/Admin/Tag/AdminTagAdd.tsx
  src/components/Admin/Tag/AdminTagBox.tsx
  src/components/Admin/Tag/AdminTagList.tsx
  src/components/EditProjectModal/SelectCategory.tsx
Labels: 🌟 Feat

#195 feat: 캘린더 개인업무 연결
  src/api/api.ts
  src/api/task.ts
  src/components/MainPage/Calendar.tsx
  src/components/Task/TaskBox.tsx
  src/components/Task/TaskList.tsx
  src/components/modals/CreateTaskModal.tsx
  src/constants/calendarColors.ts
  src/styles/Calandar.css
  src/types/task.d.ts
  src/utils/calendar/dragChangeTask.ts
Labels: 🌟 Feat

#197 Feat 마이페이지 기능 구현 / 메인페이지 시계 최적화 #177
  src/api/myPage.ts
  src/components/MainPage/TodaySchedule.tsx
  src/pages/MyPage.tsx
Labels: 🌟 Feat

#199 Fix 캘린더 프로젝트개인업무 버튼 #196
  src/components/MainPage/Calendar.tsx
  src/components/MainPage/ScheduleBox.tsx
  src/components/MainPage/TodaySchedule.tsx
  src/components/Task/TaskBox.tsx
  src/components/Task/TaskList.tsx
  src/components/modals/ConfirmModal.tsx
  src/components/modals/UpdateTaskModal.tsx
  src/styles/Calandar.css
Labels: 🌟 Feat, 🔨 Fix

#200 <Merge/feat_알람-테스트-및-구현_#191>Feat 알람 테스트 및 구현 #191
  src/api/alarm.ts
  src/components/AlamModal/AlarmBox.tsx
  src/components/Task/TaskBox.tsx
  src/components/layout/Header.tsx
  src/components/modals/AlarmModal.tsx
  src/hooks/useReadAlarm.ts
  src/store/useWebSocketStore.ts
  src/types/alarm.d.ts
Labels: 🌟 Feat

#202 fix: 남은 시간 수정
  src/components/MainPage/ScheduleBox.tsx
Labels: 🔨 Fix

#205 Fix 프로젝트 생성모달 날짜제한 수정 #198
  src/components/EditProjectModal/DateTimeSelect.tsx
  src/components/modals/EditProjectModal.tsx
  src/types/project.d.ts
Labels: 🔨 Fix

#207 <Merge/feat_미팅룸에서-알람-막기_#203>Feat 미팅룸에서 알람 막기 #203
  src/App.tsx
  src/components/MeetingRoom/MeetingRoomMessage.tsx
  src/components/layout/Header.tsx
  src/components/modals/NoteListModal.tsx
  src/store/useWebSocketStore.ts
Labels: 🌟 Feat

#209 Fix 3차qa 로그인/관리자페이지 수정 #206
  src/components/Admin/Project/AdminProject.tsx
  src/hooks/useGoogleLogin.ts
  src/pages/SignIn.tsx
Labels: 🔨 Fix

#212 Fix 관리자페이지 수정 #210
  src/api/adminCategory.ts
  src/components/Admin/Account/AdminAccount.tsx
  src/components/Admin/Account/AdminAccountList.tsx
  src/components/Admin/Project/AdminProject.tsx
  src/components/Admin/Project/AdminProjectList.tsx
  src/components/Admin/Tag/AdminTag.tsx
  src/components/Admin/Tag/AdminTagAdd.tsx
  src/components/Admin/Tag/AdminTagList.tsx
  src/types/admin.d.ts
Labels: 🔨 Fix

#215 Fix 3차qa 메인페이지 업무관련 #204
  src/components/MainPage/Calendar.tsx
  src/components/MainPage/TodaySchedule.tsx
  src/components/Task/TaskList.tsx
  src/components/layout/Header.tsx
  src/components/modals/CreateTaskModal.tsx
  src/pages/MainPage.tsx
  src/pages/ProjectRoom/ProjectRoomDetail.tsx
Labels: 🔨 Fix

#218 fix: 리프레쉬 토큰을 이용한 로그인 유지
  src/api/api.ts
Labels: 🔨 Fix

#221 Feat 마이페이지 수정기능 #213
  src/api/myPage.ts
  src/components/Admin/Account/AdminAccount.tsx
  src/components/EditProjectModal/DateTimeSelect.tsx
  src/components/EditProjectModal/WriteProjectName.tsx
  src/components/layout/AuthLayout.tsx
  src/components/modals/EditProjectModal.tsx
  src/components/modals/SimpleAlertModal.tsx
  src/pages/MyPage.tsx
  src/pages/ProjectRoom/ProjectRoom.tsx
  src/pages/SignIn.tsx
Labels: 🔍 Chore, 🌟 Feat

#222 <Merge/feat_프로젝트룸-참여인원-호버-추가_#216> feat: 참여인원호버와 스켈레톤추가 #216
  src/App.tsx
  src/components/MainPage/Calendar.tsx
  src/components/MainPage/TodaySchedule.tsx
  src/components/ProjectRoom/ProjectListBox.tsx
  src/components/common/Loading.tsx
  src/constants/socialLogin.ts
  src/hooks/useKakaoLogin.ts
  src/hooks/useReadAlarm.ts
  src/pages/KakaoRedirect.tsx
  src/pages/MainPage.tsx
  src/pages/MeetingRoom/MeetingRoom.tsx
  src/pages/ProjectRoom/ProjectRoom.tsx
Labels: 🌟 Feat

#226 Feat 관리자페이지 업무검색 #219
  src/api/search.ts
  src/components/Admin/Task/AdminTask.tsx
  src/hooks/useGoogleLogin.ts
  src/types/task.d.ts
Labels: 🌟 Feat, 🔨 Fix

#229 feat: redirects 파일 추가 #228
  public/_redirects
Labels: 🌟 Feat

#232 fix: 리다이렉트 uri 추가
  src/components/MainPage/ScheduleBox.tsx
  src/components/MainPage/TodaySchedule.tsx
  src/components/modals/UpdateTaskModal.tsx
  src/utils/signInGoogle/getAccessToken.ts
Labels: 🔨 Fix

#238 chore: 배포 오류코드 삭제
  src/components/MainPage/ScheduleBox.tsx
  src/components/MainPage/TodaySchedule.tsx
  src/components/modals/UpdateTaskModal.tsx
Labels: 🔍 Chore

#243 fix: 사이드바 새로고침 오류수정 #242
  src/components/layout/Sidebar.tsx
Labels: 🔨 Fix

#244 Fix 1차 배포 qa 업무생성편집모달 #240
  src/api/api.ts
  src/api/project.ts
  src/components/EditProjectModal/SelectMember.tsx
  src/components/MainPage/TodaySchedule.tsx
  src/components/Task/TaskBox.tsx
  src/components/Task/TaskList.tsx
  src/components/modals/CreateTaskModal.tsx
  src/components/modals/UpdateTaskModal.tsx
  src/pages/ProjectRoom/ProjectRoomDetail.tsx
  src/types/project.d.ts
  src/types/projectDetailList.d.ts
  src/types/task.d.ts
Labels: 🔥 Bug, 🌟 Feat, 🔨 Fix

#246 Feat 관리자 복구기능 구현 #241
  src/api/admin.ts
  src/components/Admin/Account/AdminAccount.tsx
  src/components/Admin/Account/AdminAccountList.tsx
  src/components/Admin/Project/AdminProject.tsx
  src/components/Admin/Project/AdminProjectList.tsx
  src/components/Admin/Task/AdminTask.tsx
Labels: 🌟 Feat

#248 Feat 개인업무업을경우문구추가 #245
  src/components/MainPage/TodaySchedule.tsx
  src/components/Task/TaskBox.tsx
  src/components/Task/TaskList.tsx
  src/pages/ProjectRoom/ProjectRoomDetail.tsx
  src/types/task.d.ts
Labels: 🔥 Bug, 🌟 Feat, 🔨 Fix

#249 <Merge/fix_1차배포qa-미팅룸회의록알람-수정_#239>fix: 1차배포qa수정 #239
  src/components/AlamModal/AlarmBox.tsx
  src/components/modals/CreateNotePeriodModal.tsx
  src/pages/ProjectRoom/ProjectRoom.tsx
  src/pages/ProjectRoom/ProjectRoomDetail.tsx
  src/store/useWebSocketStore.ts
  src/types/projectList.d.ts
Labels: 🔨 Fix

#253 Fix 마이페이지 기본이미지 변경오류 #247
  src/api/myPage.ts
  src/components/Admin/Account/AdminAccountList.tsx
  src/pages/MyPage.tsx
  src/pages/SignUpCompanyInfo.tsx
  src/types/admin.d.ts
Labels: 🔨 Fix

#255 feat: 세부 수정 #252
  src/components/AlamModal/AlarmBox.tsx
  src/components/Task/TaskList.tsx
  src/components/layout/Header.tsx
  src/components/modals/CreateNotePeriodModal.tsx
  src/pages/ProjectRoom/ProjectRoom.tsx
Labels: 🌟 Feat

#258 <Merge/feat_미팅룸-웹소켓-구독-관련_#257>feat:미팅룸웹소켓전역변경 #257
  src/components/MeetingRoom/MeetingRoomChatBox.tsx
  src/components/ProjectRoom/ProjectListBox.tsx
  src/store/useWebSocketStore.ts
Labels: 🔨 Fix

#260 Fix 워드클라우드 및 관리자업무수정취소버튼 #250
  package.json
  src/api/search.ts
  src/components/EditProjectModal/WordCloud.tsx
  src/components/Task/TaskList.tsx
  src/components/modals/CreateTaskModal.tsx
  src/components/modals/EditProjectModal.tsx
  src/components/modals/UpdateTaskModal.tsx
  src/pages/ProjectRoom/ProjectRoom.tsx
  src/pages/ProjectRoom/ProjectRoomDetail.tsx
  src/types/task.d.ts
Labels: 🌟 Feat, 🔨 Fix

#261 feat: 대그데이터 그래프 구현 #259
  src/components/Admin/Tag/AdminTag.tsx
  src/components/Admin/Tag/AdminTagChart.tsx
  src/components/Admin/Tag/TagCountBox.tsx
  src/components/layout/Header.tsx
  src/pages/ProtectedRoute.tsx
  src/store/authStore.ts
Labels: 🌟 Feat

#265 <Merge/fix_버그-수정_#262>fix: z인덱스수정 #262
  src/components/ProjectRoom/ProjectListBox.tsx
  src/components/common/AlertModal.tsx
Labels: 🔥 Bug

#266 fix: 프로젝트 리스트 버그 수정 #263
  src/components/ProjectRoom/ProjectListBox.tsx
  src/components/modals/EditProjectModal.tsx
Labels: 🔥 Bug, 🔨 Fix

#268 Fix 배포 전 qa 수정 #264
  src/components/EditProjectModal/WordCloud.tsx
  src/components/MainPage/ScheduleBox.tsx
  src/pages/MyPage.tsx
  src/pages/SignIn.tsx
Labels: 🔥 Bug, 🔨 Fix

#270 fix: 2차배포 코드정리 #269
  src/components/ProjectRoom/ProjectListBox.tsx
Labels: 🔨 Fix

#274 bug: 업무 생성 시간 오류 해결
  src/components/modals/CreateTaskModal.tsx
Labels: 🔥 Bug

#276 <Merge/fix_버그-수정_#272>fix_파비콘추가 #272
  index.html
  public/favicon.ico
  public/vite.svg
Labels: 🔨 Fix

#281 Bug 리프레쉬토큰 로그인 시 일부 기능 문제 발생 #280
  src/api/api.ts
  src/pages/MainPage.tsx
  src/pages/SignIn.tsx
Labels: 🔥 Bug

#282 <Merge/fix_회의록-로딩-오류-수정_#279>fix: 로티오류수정 #279
  src/assets/animations/AINote_loading.json
  src/assets/animations/loading_note.json
  src/components/modals/CreateAINoteModal.tsx
  src/components/modals/CreateNotePeriodModal.tsx
Labels: 🔨 Fix

#285 fix: 이미지 변경 수정
  src/pages/MyPage.tsx
Labels: 🔨 Fix

#287 fix: 마이페이지 오류 추가수정 #286
  src/pages/MyPage.tsx
Labels: 🔨 Fix

#291 <Merge/fix_404-응답값-리다이렉트-처리_#290>fix: 404 403 리다이렉트 처리 #290
  src/api/api.ts
Labels: 🔨 Fix

#292 <Merge/fix_미팅룸-채팅-불가-처리_#289>Fix 미팅룸 채팅 불가 처리 #289
  src/api/api.ts
  src/components/MeetingRoom/MeetingRoomChatBox.tsx
Labels: 🔨 Fix

#294 <Merge/fix_프로젝트룸-리다이렉트-수정_#293>fix: 프로젝트룸미팅룸리다이렉트수정 #293
  src/components/MeetingRoom/MeetingRoomChatBox.tsx
  src/pages/ProjectRoom/ProjectRoomDetail.tsx
Labels: 🔨 Fix

#296 Fix 로그인 오류수정 #278
  src/api/auth.ts
  src/api/category.ts
  src/components/Admin/Tag/AdminTagChart.tsx
  src/components/EditProjectModal/DateTimeSelect.tsx
  src/components/EditProjectModal/SelectCategory.tsx
  src/components/EditProjectModal/SelectMember.tsx
  src/components/Task/TaskBox.tsx
  src/components/Task/TaskList.tsx
  src/components/modals/CreateTaskModal.tsx
  src/components/modals/EditProjectModal.tsx
  src/components/modals/UpdateTaskModal.tsx
  src/pages/ProjectRoom/ProjectRoom.tsx
  src/pages/ProjectRoom/ProjectRoomDetail.tsx
  src/pages/SignIn.tsx
  src/store/authStore.ts
  src/types/date.d.ts
  src/types/task.d.ts
Labels: 🔨 Fix

#297 <Merge/fix_관리자페이지-분기처리_#295>fix: 관리자페이지분기처리 #295
  src/api/admin.ts
  src/api/adminCategory.ts
  src/components/Admin/Account/AdminAccount.tsx
  src/components/Admin/DashBoard.tsx
  src/components/Admin/Project/AdminProject.tsx
  src/components/Admin/Tag/AdminTag.tsx
  src/components/Admin/Task/AdminTask.tsx
  src/pages/MyPage.tsx
Labels: 🔨 Fix

#299 <Merge/fix_회의록-ampm-수정_#298>fix: 회의록 ampm 수정 #298
  src/components/NoteList/NoteListBox.tsx
  src/components/modals/CreateNotePeriodModal.tsx
  src/components/modals/NoteDetailModal.tsx
  src/utils/aiNote/dateUtils.ts
Labels: 🔨 Fix

#302 Feat 프로젝트 생성 중 로딩 추가 #267
  src/App.tsx
  src/assets/animations/loadingLottie.json
  src/components/EditProjectModal/SelectCategory.tsx
  src/components/EditProjectModal/SelectMember.tsx
  src/components/Task/TaskBox.tsx
  src/components/Task/TaskList.tsx
  src/components/modals/CreateTaskModal.tsx
  src/components/modals/EditProjectModal.tsx
  src/components/modals/UpdateTaskModal.tsx
  src/store/authStore.ts
  src/types/task.d.ts
Labels: 🌟 Feat, 🔨 Fix

#303 <Merge/feat_닉네임-중복시-처리_#301>feat: 닉네임-중복시-처리_#301
  src/api/myPage.ts
  src/pages/MyPage.tsx
  src/pages/SignUpCompanyInfo.tsx
  src/store/useWebSocketStore.ts
Labels: 🌟 Feat

#305 fix: 회원가입 후 메인 홈 오류 수정 #304
  src/api/auth.ts
  src/store/authStore.ts
Labels: 🔨 Fix

#308 <Merge/fix_알람-삭제-확인_#307>fix: 알람 삭제 수정 #307
  src/components/AlamModal/AlarmBox.tsx
Labels: 🔨 Fix

#310 fix: 로그인 페이지 디자인 수정
  src/pages/SignIn.tsx
Labels: 🎨 Design, 🔨 Fix

#314 fix: 로그아웃 오류 수정 #313
  src/components/layout/Header.tsx
Labels: 🔨 Fix

#316 Feat task drag기능 추가 #311
  package.json
  src/api/task.ts
  src/components/Task/TaskBox.tsx
  src/components/Task/TaskList.tsx
  src/components/common/LoadingLottie.tsx
  src/pages/ProjectRoom/ProjectRoomDetail.tsx
  src/utils/progressType.ts
Labels: 🌟 Feat

#318 fix: 메인 비회원 배경이미지 최적화 #317
  src/assets/auth_background.svg
  src/assets/auth_background.webp
  src/assets/guestMainBg.webp
  src/components/MainPage/GuestMain.tsx
  src/components/layout/AuthLayout.tsx
  src/dummyData/dummy.ts
Labels: 🔨 Fix
